### ISSUE TITLE
Create users detail/create/update/delete pages

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#120]
- [x] Adds ability to create a new user or update an existing user and integrate on the list page - #149 
- [x]  Adds ability to view user details. - #143 
- [x]  On list page:
  - [x]   Adds ability to activate/deactivate an existing user - #122  
  - [x]  Adds ability to delete an existing user - #144
