### ISSUE TITLE
Add e2e test cases to verify user create, view, update and delete flows

### ISSUE THREAD

**Issue by vishal423** [jhipster/generator-jhipster-svelte#150]
Add end to end tests to verify:
- [x] Create user flow - Resolved by #238 
- [x] Update user flow - Resolved by #239 
- [x] View user details flow - Resolved by #237 
- [x] Delete user flow - Resolved by #236
